version: "3.9"  # optional since v1.27.0
services:
  typesense:
    image: typesense/typesense:0.24.0
    entrypoint: sh -c "/opt/typesense-server --data-dir /data --api-key=xyz --enable-cors"
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
volumes:
  typesense-data:
    driver: local

